#!/bin/bash

plugin=$1
branch=$2
project=$3

git checkout -- tools/bzl/plugins.bzl

extension=''
if [[ "`uname`" == 'Darwin' ]]; then
  extension='.bak'
fi

sed -i "$extension" 's/# Add custom core plugins here/# Add custom core plugins here\
    \"'"$plugin"'\",/' \
  tools/bzl/plugins.bzl && \
sed -i "$extension" 's/# Add custom core plugins with tests deps here/# Add custom core plugins with tests deps here\
    \"'"$plugin"'\",/' \
  tools/bzl/plugins.bzl && \
rm tools/bzl/plugins.bzl.bak && \
ln -sf "$HOME"/git/gerrit/"$project"/"$branch"/"$plugin" plugins/ && \
cp plugins/"$plugin"/external_plugin_deps.bzl plugins/
