#!/bin/bash

suffix=$1

branch=${PWD##*/}
testsite=$HOME/git/gerrit/testsites/$branch$suffix

gbash-clean-site "$suffix"

bazel build release && \
bazel shutdown && \
"$(bazel info output_base)"/external/local_jdk/bin/java -jar \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
  bazel-bin/release.war init \
  --dev \
  --install-all-plugins \
  -d "$testsite"

tail -f "$testsite"/logs/error_log
