#!/bin/bash

branch=${PWD##*/}
from=$1

gbash-update

git submodule foreach git fetch && \
git submodule foreach git checkout origin/master && \

git submodule foreach "git branch -D $from || echo no branch" && \
git submodule foreach "git checkout -t origin/$from && git pull || echo no branch" && \

git submodule foreach "git branch -D $branch || echo no branch" && \
git submodule foreach "git checkout -t origin/$branch && git pull || echo no branch" && \

git submodule foreach "git merge $from --no-commit --no-ff || echo no merge"
git submodule foreach git status
git status
