#!/bin/bash

plugin=$1
branch=$2
project=$3

ln -sf "$HOME"/git/gerrit/"$project"/"$branch"/"$plugin" plugins/ && \
cp plugins/"$plugin"/external_plugin_deps.bzl plugins/

sed -i 's/# Add custom core plugins here/# Add custom core plugins here\n    \"'"$plugin"'\",/' ./tools/bzl/plugins.bzl
