#!/bin/bash

export branch=${PWD##*/}
export core=$1

# shellcheck disable=SC2016
git status|grep modified:|awk '{print $2}'|xargs -I % sh -c '
  cd $HOME/git/gerrit/plugins &&
  gbash-test-standalone % $branch &&
  cd - &&
  cd $HOME/git/gerrit/core/$core &&
  gbash-test-intree % $branch plugins &&
  gbash-uninstall-intree % &&
  cd -'
