#!/bin/bash

from=$1
branch=$2

git stash
git fetch && \
git checkout origin/"$branch" && \

git branch -D "$from" || echo no branch && \
git checkout -t origin/"$from" && git pull || echo no branch && \

git branch -D "$branch" || echo no branch && \
git checkout -t origin/"$branch" && git pull && \

git merge "$from" --no-commit --no-ff || echo no merge && \

git status|grep deleted|awk '{print $4}'|xargs -I % sh -c '
  git rm %'
