#!/bin/bash

site=$1
testsite=$HOME/git/gerrit/testsites/$site

bazel build release && \
bazel shutdown && \
"$(bazel info output_base)"/external/local_jdk/bin/java -jar \
  bazel-bin/release.war init \
  --batch \
  --dev \
  --install-all-plugins \
  --no-auto-start \
  -d "$testsite"
