#!/bin/bash

gbash-stop-site

branch=${PWD##*/}
testsite=$HOME/git/gerrit/testsites/${branch}

rm -fr "$testsite"

gbash-build-gerrit

bazel build release && \
"$(bazel info output_base)"/external/local_jdk/bin/java -jar \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
  bazel-bin/release.war init \
  --batch \
  --dev \
  --install-all-plugins \
  -d "$testsite"

bazel shutdown

tail -f "$testsite"/logs/error_log
