#!/bin/bash

export branch=${PWD##*/}
export core=$1
plugin=$2

cd "$HOME"/git/gerrit/core/"$core" && \
gbash-rebuild-gerrit && \
cd - || exit

# shellcheck disable=SC2016
git status|grep modified:|grep "$plugin"|awk '{print $2}'|xargs -I % sh -c '
  cd $HOME/git/gerrit/plugins &&
  gbash-test-standalone % $branch &&
  cd - &&
  cd $HOME/git/gerrit/core/$core &&
  gbash-test-intree % $branch plugins &&
  gbash-uninstall-intree % &&
  cd -'

cd "$HOME"/git/gerrit/core/"$core" && \
bazel shutdown && \
cd - || exit
