#!/bin/bash

branch=$1
testsite=$HOME/git/gerrit/testsites/$branch

gbash-stop-branch-there "$branch"

bazel build release && \
bazel shutdown && \
"$(bazel info output_base)"/external/local_jdk/bin/java -jar \
  bazel-bin/release.war init \
  --install-all-plugins \
  --no-auto-start \
  -d "$testsite"

"$testsite"/bin/gerrit.sh start
tail -f "$testsite"/logs/error_log
