#!/bin/bash

branch=$1
from=$2
unless=$3

gbash-plugins-update-push

git submodule foreach git checkout origin/"$branch" && \

git submodule foreach "git branch -D $unless || \
  git branch -D $from || echo no branch" && \
git submodule foreach "git checkout -t origin/$unless && git pull || \
  git checkout -t origin/$from && git pull || echo no branch" && \

git submodule foreach "git branch -D $branch || echo no branch" && \
git submodule foreach "git checkout -t origin/$branch && git pull" && \

git submodule foreach "git merge $unless --no-commit --no-ff || \
  git merge $from --no-commit --no-ff || echo no merge"
git status
