#!/bin/bash

gbash-stop-site $1

testsite=$HOME/git/gerrit/testsites/testsite$1

bazel build release && \
bazel shutdown && \
"$(bazel info output_base)"/external/local_jdk/bin/java -jar \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 \
  bazel-bin/release.war daemon \
  -d "$testsite" \
  --console-log
