#!/bin/bash

suffix=$1

branch=${PWD##*/}
testsite=$HOME/git/gerrit/testsites/$branch$suffix
from=$testsite/../$branch/etc/gerrit.config
to=$testsite/etc/gerrit.config
serverId=$(awk '/serverId/{print $NF}' "$from")

gbash-clean-site "$suffix"

"$(bazel info output_base)"/external/local_jdk/bin/java -jar \
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5006 \
  bazel-bin/release.war init \
  --dev \
  --install-all-plugins \
  --no-auto-start \
  -d "$testsite"

extension=''
if [[ "$(uname)" == 'Darwin' ]]; then
  extension='.bak'
fi
sed -i "$extension" -E "s/(serverId = ).+/\1$serverId/" "$to"

gbash-restart-site "$suffix"
