#!/bin/bash
#
# -Usage example; informal script:
# gbash-update-release-notes 3.3.0-rc0 3.2.3

# shellcheck disable=SC2016

version=$1
since=$2
# shellcheck disable=SC2140
log="v$since".."v$version"

export issue=": Issue "
excluded="Update git submodules"
git log "$log" --grep="$issue" --oneline | grep -v "$excluded" > gbash-update-release-notes_issue-Subject

rm -f gbash-update-release-notes_issue-ID
awk '{print $1}' < gbash-update-release-notes_issue-Subject | xargs -I % sh -c '
  issued=$(git log % -n 1 | grep "$issue" | awk "ORS=\" \"") &&
  echo "% $issued" >> gbash-update-release-notes_issue-ID'

extension=''
backup='bak'
if [[ "$(uname)" == 'Darwin' ]]; then
  extension='.'$backup
fi

sed -i "$extension" 's/ [^0-9]*: [^0-9]*/ /g' gbash-update-release-notes_issue-ID
sed -i "$extension" 's/, Issue//g' gbash-update-release-notes_issue-ID
rm -f gbash-update-release-notes_issue-ID.$backup

rm -f gbash-update-release-notes_issue-md
awk '{print $2}' < gbash-update-release-notes_issue-ID | xargs -I % sh -c '
  echo "\n  * [Issue %](https://bugs.chromium.org/p/gerrit/issues/detail?id=%):\n    Subject" >> gbash-update-release-notes_issue-md'

sed -i "$extension" 's/^[^ ]* //g' gbash-update-release-notes_issue-Subject
sed -i "$extension" 's/\//|/g' gbash-update-release-notes_issue-Subject
rm -f gbash-update-release-notes_issue-Subject.$backup

while read -r subject; do
  sed -i "$extension" "1,/Subject/s/Subject/$subject./" gbash-update-release-notes_issue-md
done < gbash-update-release-notes_issue-Subject
rm -f gbash-update-release-notes_issue-md.$backup

awk '{print $3}' < gbash-update-release-notes_issue-ID | xargs -I % sh -c '
  echo "\n  * [Issue %](https://bugs.chromium.org/p/gerrit/issues/detail?id=%):\n    Subject" >> gbash-update-release-notes_issue-md'
awk '{print $4}' < gbash-update-release-notes_issue-ID | xargs -I % sh -c '
  echo "\n  * [Issue %](https://bugs.chromium.org/p/gerrit/issues/detail?id=%):\n    Subject" >> gbash-update-release-notes_issue-md'

rm gbash-update-release-notes_issue-ID
rm gbash-update-release-notes_issue-Subject

# TODO: include Update git submodules.
# TODO: --invert-grep, for non-Issues.
